print ("FFFFFFF   U     U  NN     NN")
print ("FF        U     U  NNN    NN")
print ("FFFFFFF   U     U  N  N   NN")
print ("FF         U   U   N   N  NN")
print ("FF          UUU    N     NNN")
